name: Demo CI/CD Workflow Call
on:
    push:
        branches:
            - main 
    workflow_dispatch:     
            inputs:
                valor:
                    type: string
                    description: 'texto qualquer'
                    required: true
                    default: 'Um valor qualquer'
                carro:
                    type: string
                    description: 'Carro'
                    required: true
                    default: 'Fusca'
                pais:
                    type: string
                    description: 'Local'
                    required: true
                    default: 'Brasil'
                cidade:
                    type: string
                    description: 'Cidade'
                    required: false
                    default: 'São Paulo'

jobs: 
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.5
            - name: Autenticação no Docker Hub
              uses: docker/login-action@v3.1.0
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build da Imagem Docker
              run: echo "Imagem Docker construída com sucesso!"
    CD:
      needs: [CI]
      uses: casoftsolutions/usando-workflow-call/.github/workflows/cd.yaml@main

    CD-Feature:
      needs: [CI]
      uses: casoftsolutions/usando-workflow-call/.github/workflows/feature.yaml@feature
    #   with: 
    #     valor: ${{ inputs.valor }}
    #     carro: ${{ inputs.carro }}
    #     pais: ${{ inputs.pais }}
    #     cidade: ${{ inputs.cidade }}